Z_LIMIT = 80            # LIMITATION ON Z AXIS
Z_STEP = 0.0005         # 
BEAMWIDTH = 5
COUPLING_COEF_1 = 1
COUPLING_COEF_2 = 0.5
SIGMA = -1.2            # DIRAC MASS
GAMMA = 1               # NONLINEARITY
COL_NUM = 121           # COLUMN NUMBER
ROW_NUM = 121           # ROW NUMBER

FRAME_NUM = 80



